---
title: "README"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

This Repository houses all the work necessary to complete the final project for the DAT 410 course at Southern New Hampshire University.  Specifically, it is done for the 'Medical' portion as there are 3 choices to pick from _(similar to pokemon)_.

This readme will also keep track of the different steps completed and when the full project is done.

## Case Details

Healthcare Case: The healthcare case uses 2002 through 2012 Centers for Disease Control and
Prevention (CDC) health statistics found at [http://www.cdc.gov/nchs/](http://www.cdc.gov/nchs/).

*Case*: A drugstore is developing an extended service for those who signed up for the customer
care program. The drugstore knows how many program members they have by store and are
looking to create characteristic multiplier factors that can be applied to the program members
to provide a customized marketing model. In your role as a data analyst, you have been asked to
perform decision support analysis and present the information to the customer care program
team.

There are three Excel files in the healthcare folder: Chronic Illness, Insurance, and Vaccinations.
The data that has been provided is percentages from 2002 to 2012 for a variety of label
categories and characteristics. For each dataset, there are different labels and characteristics by
design to generate independent findings for each result.

For chronic illness, provide the top three label/characteristics for each group: 1 chronic illness,
2–3 chronic illness, and 4+ chronic illness. For the identified top three, generate a multiplier and
coefficient by forecasting the next value using 2002 through 2012.

For insurance, provide the top five label/characteristics of Dataset InsCoverageUnder65.
Additionally, provide the bottom five label/characteristics of Dataset NoInsurance.

For vaccinations, provide the top three label/characteristics. Using the top five
label/characteristics from the insurance data, attempt to align to the vaccinations and provide 
average, min, max for any matching item. For the identified top three label/characteristics,
generate a multiplier for each the pneumonia vaccine counts and the influenza counts.
